routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/command', function() {
//     $output = [];
//     \Artisan::call('migrate:fresh', $output);
//     dd($output);
// });
Route::get('/contact','FrontendController@index');
Route::get('/track-parcel','FrontendController@Showtracking');
Route::get('/about-us','FrontendController@Aboutus');
Route::get('/services','FrontendController@services');
Route::resource('send-parcel','SendParcelController');
Route::post('/contact-process','ContactController@store')->name('contact.store');
Auth::routes();
// ['register' => false]
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout','HomeController@logout');

Route::get('track-order','WebController@track_order')->name('track_order');

// Route::group(['middleware' => 'auth']{
   

// });
Route::group(['middleware'=> ['admin']],function(){
    Route::get('/admin/dashboard', 'AdminController@index')->name('admin');
    Route::resource('parcel','ParcelController');
    Route::post('/add-log', 'ParcelController@add_log')->name('add_log');
    Route::post('/delete-log/{id}', 'ParcelController@delete_log')->name('delete_log');
    
});

resources/views/about.blade.php
@extends('layouts.app')
@section('title')
About
@endsection
@php
    $append_ = env('MY_ASSET_URL');
@endphp
@section('content')
<div class="slider-area mb-5">
    <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background=" {{asset($append_ .'assets2/img/hero/parcelbox.jpg')}}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>About Us</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
<div class="container mb-5">
              <!-- Support Company Start-->
<div class="support-company-area support-padding fix mt-5">
<div class="container">
    <div class="row align-items-center">
        <div class="col-xl-6 col-lg-6">
            <div class="right-caption">
                <!-- Section Tittle -->
                <div class="section-tittle section-tittle2">
                    <span>What we are doing</span>
                    <h2 style="font-weight: 900;font-size:35px;">We’re TRUSTED by our customers & retailers</h2>
                </div>
                <div class="support-caption">
                    <p class="pera-top">We cover different industry sectors, from food and beverage, chemical, retail, durable goods and more. Check the full list...</p>
                    <p>We have a dedicated team of friendly helpful staff ready and waiting to receive your call and to ensure that your urgent consignments arrive safely as planned, time and time again.</p>
                    <a href="/track-parcel" class="btn post-btn">Track a parcel</a>
                </div>
            </div>
        </div>
        <div class="col-xl-6 col-lg-6">
            <div class="support-location-img">
                <img src=" {{asset($append_ .'assets2/img/hero/parcelbox2.jpg')}}" alt="">
            </div>
        </div>
    </div>
</div>
</div>
<!-- Support Company End-->
</div>
@endsection

resources/views/home.blade.php
{{--  @extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard <span style="float: right"><button class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#addparcel">Add Parcel</button></span></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                <div class="">
                    <table class="table responsive">
                        <thead>
                            <th>Parcel</th>
                            <th>Tracking No.</th>
                            <th>Sender</th>
                            <th>Receiver</th>
                            <th>Current Location</th>
                            <th>Pick-up</th>
                            <th>Drop-off</th>
                            <th>Fee</th>
                            <th>Status</th>
                            <th>Creation Date</th>
                            <th>Actions</th>
                        </thead>
                        <tbody>
                        @foreach($parcels as $parcel)
                        @php($curr_location = App\ParcelLog::where('parcel_id',$parcel->id)->orderby('created_at','desc')->first())
                            <tr>
                                <td> {{$parcel->parcel_name}} </td>
                                <td> {{$parcel->track_no}} </td>
                                <td> {{$parcel->sender_name}} </td>
                                <td> {{$parcel->receiver_name}} </td>
                                @if(empty($curr_location))
                                <td> Not Available </td>
                                @else
                                <td>{{$curr_location->curr_location}}</td>
                                @endif
                                <td> {{$parcel->pickup_location}} </td>
                                <td> {{$parcel->receiver_address}} </td>
                                <td> {{$parcel->fee}} </td>
                                <td> {{$parcel->status}} </td>
                                <td> {{$parcel->created_at->format('Y-M-d')}} </td>
                                <td>
                                    <a href="" class="btn btn-outline-success btn-sm">View</a>
                                    <a href="{{ route('parcel.show',$parcel) }}" class="btn btn-outline-info btn-sm">Log</a>
                                    <a href="" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#del-{{$parcel->id}}">Delete</a>

                                    <div class="modal fade bd-example-modal-md" id="del-{{$parcel->id}}">
                                        <div class="modal-dialog modal-dialog-centered modal-md" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header mb-3">
                                                    <h5 class="modal-title">Delete Parcel </h5>
                                                    <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
                                                </div>
                                                <div class="modal-body">
                                                Are you sure? Deleting this would also delete all logs related to this item
                                                <form action="{{ route('parcel.destroy',$parcel)}}" method="post">@csrf @method('delete')
                                                    <div class="modal-footer">
                                                        <button class="btn btn-outline-info btn-sm" type="button" class="close" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-outline-danger btn-sm" >Proceed</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bd-example-modal-lg" id="addparcel">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
          <div class="modal-content">
              <div class="modal-header mb-3">
                  <h5 class="modal-title">Add Parcel </h5>
                  <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
              </div>
              <div class="modal-body">
                  <form action="{{ route('parcel.store') }}" method="post">@csrf
                  <div class="row">
                      <div class="col-md-6">
                        <div class="form-group mb-2 ">
                            <label for="">Sender Name</label>
                            <input type="text" name="sender_name" class="form-control" required value="{{old('sender_name')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Sender Email</label>
                            <input type="email" name="sender_email" class="form-control" required value="{{old('sender_email')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Sender Phone Number</label>
                            <input type="number" name="sender_phone" class="form-control" required value="{{old('sender_phone')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Parcel Name</label>
                            <input type="text" name="parcel_name" class="form-control" required value="{{old('parcel_name')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Pickup Country</label>
                            <input type="text" name="pickup_location" class="form-control" required value="{{old('pickup_location')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Pickup State</label>
                            <input type="text" name="pickup_location" class="form-control" required value="{{old('pickup_location')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Pickup Location</label>
                            <input type="text" name="pickup_location" class="form-control" required value="{{old('pickup_location')}}">
                        </div>
                      </div>

                    <div class="col-md-6">
                        <div class="form-group mb-2">
                            <label for="">Receiver Name</label>
                            <input type="text" name="receiver_name" class="form-control" required value="{{old('receiver_name')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Receiver Phone Number</label>
                            <input type="text" name="receiver_phone" class="form-control" required value="{{old('receiver_phone')}}">
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Receiver Address</label>
                            <textarea type="text" rows="3" name="receiver_address" class="form-control" required>{!! old('receiver_address') !!}</textarea>
                        </div>
                        <div class="form-group mb-2">
                            <label for="">Delivery Fee (NGN)</label>
                            <input type="number" name="fee" class="form-control" required value="{{old('fee')}}">
                        </div>
                        <div class="control-group">
                            <button type="submit" class="btn btn-blue">Proceed</button>
                        </div>
                    </div>
                </div>
              </div>
              </form>
          </div>
      </div>
  </div>

  <div class="modal fade bd-example-modal-lg" id="addparcel">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
          <div class="modal-content">
              <div class="modal-header mb-3">
                  <h5 class="modal-title">Add Parcel </h5>
                  <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
              </div>
              <div class="modal-body">

          </div>
      </div>
  </div>


@endsection  --}}
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/parcel_log.blade.php
@extends('admin.layout.master')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header h4"> <b>{{$parcel->parcel_name}}</b> #{{$parcel->track_no}} <span style="float: right"><a href="{{ route('parcel.index') }}" class="btn btn-outline-dark btn-sm">Back to Parcels</a> 
                 <button class="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#addparcel">Add Parcel Log</button></span></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                <div class="">
                    <table class="table responsive">
                        <thead>
                            <th>Added By</th>
                            <th>Previous Location</th>
                            <th>New Location</th>
                            <th>Update Time</th>
                            <th>Actions</th>
                        </thead>
                        <tbody>
                        @foreach($logs as $log)
                            <tr>
                                <td>{{$log->admin->name}}</td>
                                <td>{{$log->prev_location}}</td>
                                <td>{{$log->curr_location}}</td>
                                <td>{{ $log->created_at->format('Y M d , h:i:A')}}</td>
                                <td>
                                   
                                    <a href="" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#del-{{$log->id}}">Delete</a>
                                    
                                    <div class="modal fade bd-example-modal-md" id="del-{{$log->id}}">
                                        <div class="modal-dialog modal-dialog-centered modal-md" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header mb-3">
                                                    <h5 class="modal-title">Delete Parcel </h5>
                                                    <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
                                                </div>
                                                <div class="modal-body">
                                                Are you sure? Deleting this would also delete all logs related to this item
                                                <form action="{{ route('delete_log',$log)}}" method="post">@csrf 
                                                    <div class="modal-footer">
                                                        <button class="btn btn-outline-info btn-sm" type="button" class="close" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-outline-danger btn-sm" >Proceed</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade bd-example-modal-md" id="addparcel">
      <div class="modal-dialog modal-dialog-centered modal-md" role="document">
          <div class="modal-content">
              <div class="modal-header mb-3">
                  <h5 class="modal-title">Add Parcel Log </h5>
                  <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
              </div>
              <div class="modal-body">
                  <form action="{{ route('add_log') }}" method="post">@csrf
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group mb-2 ">
                        @php($curr_location = App\ParcelLog::where('parcel_id',$parcel->id)->orderby('created_at','desc')->first())
                            <label for="">Previous Location</label>
                            <input type="hidden" name="parcel_id" class="form-control" required value="{{$parcel->id}}">
                            @if(empty($curr_location->curr_location))
                            <input type="text" name="prev_location" class="form-control" required value="{{old('prev_location') ?? $parcel->pickup_location}}">
                            @else
                            <input type="text" name="prev_location" class="form-control" readonly required value="{{$curr_location->curr_location}}">
                            @endif
                        </div> 
                        <div class="form-group mb-2">
                            <label for="">New Location</label>
                            <input type="text" name="curr_location" class="form-control" required value="{{old('curr_location')}}">
                        </div> 
                        
                        <div class="control-group">
                            <button type="submit" class="btn btn-primary">Proceed</button>
                        </div>
                    </div> 
                </div> 
              </div>
              </form>
          </div>
      </div>
  </div>

  <div class="modal fade bd-example-modal-lg" id="addparcel">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
          <div class="modal-content">
              <div class="modal-header mb-3">
                  <h5 class="modal-title">Add Parcel </h5>
                  <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></h5>
              </div>
              <div class="modal-body">

          </div>
      </div>
  </div>
@endsection

resources/views/parcel_send.blade.php
@extends('layouts.app')
@section('title')
Send a Parcel
@endsection
@php
    $append_ = env('MY_ASSET_URL');
@endphp
@section('content')
    <!-- Hero Area Start-->
    <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center" data-background=" {{asset($append_ .'assets2/img/hero/parcelbox.jpg')}}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Send a Parcel</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!-- Hero Area End -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section">
            <div class="container">    
                <div class="row">
                    <div class="col-12 mb-5">
                        <h2 class="contact-title text-center">Send a parcel from £2.45 (£2.05 + VAT) </h2>
                    </div>
                    <div class="col-lg-6">
                        <form class="form-contact contact_form" action="{{route('send-parcel.store')}}" method="post">
                            @csrf
                            <div class="row">
                                 <div class="col-12">
                                    <h2 class="contact-title">Your Address</h2>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid @error('sender_name') is-invalid @enderror border border-secondary" name="sender_name" id="sender_name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your Name'" placeholder="Enter your Name">
                                         @error('sender_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                      <div class="form-group">
                                        <input class="form-control valid @error('sender_email') is-invalid @enderror border border-secondary" name="sender_email" id="sender_email" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your Email'" placeholder="Enter your Email Address">
                                         @error('sender_email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                      <div class="form-group">
                                        <input class="form-control valid @error('sender_phone') is-invalid @enderror border border-secondary" name="sender_phone" id="sender_phone" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your sender_phone'" placeholder="Enter your Phone Number">
                                         @error('sender_phone')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                      <div class="form-group">
                                      <label class="font-weight-bold">Address:</label>
                                       <textarea class="form-control w-100 @error('sender_phone') is-invalid @enderror border border-secondary" name="sender_address" id="sender_address" cols="30" rows="5" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Home Address'" placeholder=" Enter Home Address">
                                       </textarea>  
                                         {{-- @error('sender_address')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror                                        --}}
                                    </div>
                                </div>
                                <div class="col-12">
                                      <div class="form-group">
                                        <input class="form-control valid @error('parcel') is-invalid @enderror border border-secondary" name="parcel" id="parcel" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your Parcel'" placeholder="Enter your Parcel Item">
                                         @error('parcel')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                      <div class="form-group">
                                        <input class="form-control valid @error('weight') is-invalid @enderror border border-secondary" name="weight" id="weight" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your Item Weight'" placeholder="Enter your Item Weight ">
                                         @error('weight')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="row">
                                <div class="col-12">
                                    <h2 class="contact-title">Receiver Address</h2>
                                </div>
                                 <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid @error('receiver_name') is-invalid @enderror border border-secondary" name="receiver_name" id="receiver_name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Receiver Name'" placeholder="Enter Receiver Name">
                                         @error('receiver_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                 <div class="col-sm-6">
                                    <div class="form-group">
                                        <input class="form-control valid @error('receiver_email') is-invalid @enderror border border-secondary" name="receiver_email" id="receiver_email" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Receiver Email'" placeholder="Enter Receiver Email">
                                         @error('receiver_email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                 <div class="col-sm-12">
                                    <div class="form-group">
                                        <input class="form-control valid @error('receiver_phone') is-invalid @enderror border border-secondary" name="receiver_phone" id="receiver_phone" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Receiver Phone Number'" placeholder="Enter Receiver Phone Number">
                                         @error('receiver_phone')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror
                                    </div>
                                </div>
                                <div class="col-12">
                                      <div class="form-group">
                                      <label class="font-weight-bold">Address:</label>
                                       <textarea class="form-control w-100 @error('receiver_address') is-invalid @enderror border border-secondary" name="receiver_address" id="receiver_address" cols="30" rows="5" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Receiver Home Address'" placeholder=" Enter Receiver Home Address">
                                       </textarea>  
                                         {{-- @error('sender_address')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                         @enderror                                        --}}
                                    </div>
                                </div>
                    </div>
                </div>
            </div>
              <div class="form-group mt-3">
                <button type="submit" class="button button-contactForm boxed-btn">Send</button>
            </div>
            </form>
        </section>
@endsection